config/routes.rb
Rails.application.routes.draw do

  resources :students, only: [:index, :show, :new]
  resources :assignments, only: [:index, :show, :new]

  root 'students#index'

end

app/models/assignment.rb
class Assignment < ActiveRecord::Base
  # You have a good setup for your models in terms of associations, I think
  # a good next step would be to update your UI so that you can use the
  # associations for the users to associate students and assignments
  belongs_to :student
end

app/models/student.rb
class Student < ActiveRecord::Base
  has_many :assignments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception



end

app/controllers/assignments_controller.rb
class AssignmentsController < ApplicationController

  # I noticed a lot of duplication between the students index and the
  # assignments index... they both show the exact same info (list of
  # students and assingments)
  def index
    @students = Student.all
    @assignments = Assignment.all
  end

  def show
    @assignment = Assignment.find(params[:id])
  end

  def new
    @assignment = Assignment.new
  end

  def create
    # @assignment = Assignment.create!(assignment_params)
    # flash[:notice] = "Assignment created successfully!"
    # redirect_to @assignment
    # if params[:assignment][:name] == ""
    #   flash[:alert] = "Assignment can't be blank!"
    #   redirect_to @assignment
    # else
    #   @assignment = Assignment.create(assignment_params)
    #   redirect_to @assignment
    # end
  end

  def destroy
    @assignment = Assignment.find(params[:id])
    @assignment.destroy
    redirect_to assignments_path
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  def index
    @students = Student.all
    @assignments = Assignment.all
  end

  def show
    @student = Student.find(params[:id])
  end

  def new
    @student = Student.new
  end

  def create
    # this code is a bit confusing and would cause problems when trying to
    # create a student with a blank name. It looks like you copied code
    # from the lesson on validations, but that code was flagged in the LP
    # as being *not* the ideal way to approach validation. Make sure you're
    # thinking through what code does when copying!

    @student = Student.create!(student_params)
    flash[:notice] = "student created successfully!"
    redirect_to @student
    if params[:student][:name] == ""
      flash[:alert] = "Student can't be blank!"
      redirect_to @student
    else
      @student = Student.create(student_params)
      redirect_to @student
    end
  end

  def destroy
    @student = student.find(params[:id])
    @student.destroy
    redirect_to students_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/assignments_helper.rb
module AssignmentsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/assignments/index.html.erb
<h2><%= link_to 'New Assignment', assignments_path %></h2>

<h1>List of Assignments</h1>
<ul>
  <% @assignments.each do |assignment| %>
    <li>
      <%= link_to assignment.name, assignment_path(assignment) %>
    </li>
  <% end %>
</ul>


<h4>Go to Students</h4>
<ul>
  <% @students.each do |student| %>
    <li>
      <%= link_to student.name, student_path(student) %>
      <% student.assignments.each do |assignment| %>
        <%= link_to assignment.name, assignment_path(assignment) %>
      <% end %>
    </li>
  <% end %>
</ul>

app/views/assignments/show.html.erb
<h1><%= link_to "Assignments", assignments_path %></h1>
  <li>
    <strong>Listed Assignment:</strong>
    <p><%= @assignment.name %></p>
    <strong>Topic or Subject:</strong>
    <p><%= @assignment.subject %></p>
    <strong>Earned Grade/Mark:</strong>
    <p><%= @assignment.grade %></p>
  </li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AssignmentTracker</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/students/index.html.erb
<!--  this link should go to the new_student_path -->
<h2><%= link_to "New Student", students_path %></h2>


<h1>List of Students</h1>
<ul>
  <% @students.each do |student| %>
    <li>
      <%= link_to student.name, student_path(student) %>
    </li>
  <% end %>
</ul>

<h4>Go to Assignments</h4>
<ul>
  <% @assignments.each do |assignment| %>
    <li>
      <%= link_to assignment.name, assignment_path(assignment) %>
    </li>
  <% end %>
</ul>

app/views/students/new.html.erb
<h2>New Student</h2>

<!-- this form will probably generate an error... the variable should be @student
singular, and the attributes don't line up with a students attributes. -->
<%= form_for @students do |f| %>
  <%= f.label :body %>
  <%= f.text_field :body %>

  <%= f.label :author %>
  <%= f.text_field :author %>

  <%= f.submit %>
<% end %>

app/views/students/show.html.erb
<h1><%= link_to "Students", students_path %></h1>
  <li>
    <strong>Student:</strong>
    <p><%= @student.name %></p>
    <strong>Grade Level:</strong>
    <p><%= @student.grade_level %></p>
  </li>